name: 3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - tqdm
  - plyfile
  - ninja
  - matplotlib
  - imageio
  - ffmpeg
  - pip:
      - torch==2.2.2+cu121
      - torchvision==0.17.2+cu121
      - torchaudio==2.2.2+cu121
      - opencv-python
      - imageio[ffmpeg]
      - lpips
      - gdown
      - joblib
      - wandb
      - ./submodules/diff-gaussian-rasterization
      - ./submodules/simple-knn
      - ./submodules/fused-ssim
