_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
data_device:
    value: cuda
depths:
    value: ""
eval:
    value: true
images:
    value: images
model_path:
    value: ./output/4fb20286-e
resolution:
    value: -1
sh_degree:
    value: 3
source_path:
    value: D:\Sem 242\Specialized project\mip
train_test_exp:
    value: false
white_background:
    value: false
